In [1]:
import pathlib
import fastdup

import numpy as np
import matplotlib.pyplot as plt
import warnings
import json
import pandas as pd

# Utility functions
Coped from https://github.com/huggingface/notebooks/blob/main/examples/segment_anything.ipynb

In [2]:
def show_mask(mask, ax, random_color=False):
    if random_color:
        color = np.concatenate([np.random.random(3), np.array([0.6])], axis=0)
    else:
        color = np.array([30 / 255, 144 / 255, 255 / 255, 0.6])
    h, w = mask.shape[-2:]
    mask_image = mask.reshape(h, w, 1) * color.reshape(1, 1, -1)
    ax.imshow(mask_image)


def show_box(box, ax):
    x0, y0 = box[0], box[1]
    w, h = box[2] - box[0], box[3] - box[1]
    ax.add_patch(
        plt.Rectangle((x0, y0), w, h, edgecolor="green", facecolor=(0, 0, 0, 0), lw=2)
    )


def show_boxes_on_image(raw_image, boxes):
    plt.figure(figsize=(10, 10))
    plt.imshow(raw_image)
    for box in boxes:
        show_box(box, plt.gca())
    plt.axis("on")
    plt.show()


def show_points_on_image(raw_image, input_points, input_labels=None):
    plt.figure(figsize=(10, 10))
    plt.imshow(raw_image)
    input_points = np.array(input_points)
    if input_labels is None:
        labels = np.ones_like(input_points[:, 0])
    else:
        labels = np.array(input_labels)
    show_points(input_points, labels, plt.gca())
    plt.axis("on")
    plt.show()


def show_points_and_boxes_on_image(raw_image, boxes, input_points, input_labels=None):
    plt.figure(figsize=(10, 10))
    plt.imshow(raw_image)
    input_points = np.array(input_points)
    if input_labels is None:
        labels = np.ones_like(input_points[:, 0])
    else:
        labels = np.array(input_labels)
    show_points(input_points, labels, plt.gca())
    for box in boxes:
        show_box(box, plt.gca())
    plt.axis("on")
    plt.show()


def show_points(coords, labels, ax, marker_size=375):
    pos_points = coords[labels == 1]
    neg_points = coords[labels == 0]
    ax.scatter(
        pos_points[:, 0],
        pos_points[:, 1],
        color="green",
        marker="*",
        s=marker_size,
        edgecolor="white",
        linewidth=1.25,
    )
    ax.scatter(
        neg_points[:, 0],
        neg_points[:, 1],
        color="red",
        marker="*",
        s=marker_size,
        edgecolor="white",
        linewidth=1.25,
    )


def show_masks_on_image(raw_image, masks, scores):
    if len(masks.shape) == 4:
        masks = masks.squeeze()
    if scores.shape[0] == 1:
        scores = scores.squeeze()

    nb_predictions = scores.shape[-1]
    fig, axes = plt.subplots(1, nb_predictions, figsize=(15, 15))

    for i, (mask, score) in enumerate(zip(masks, scores)):
        mask = mask.cpu().detach()
        axes[i].imshow(np.array(raw_image))
        show_mask(mask, axes[i])
        axes[i].title.set_text(f"Mask {i+1}, Score: {score.item():.3f}")
        axes[i].axis("off")
    plt.show()

In [3]:
SPLIT_MAP = dict(train="train", val="val", test="test")


def process_images(data: dict):
    df = pd.json_normalize(data["images"])
    df = df[["id", "file_name"]]
    df = df.rename(columns={"id": "image_id", "file_name": "filename"})
    return df


def process_annotations(data: dict):
    df = pd.json_normalize(data["annotations"])
    df = df[["image_id", "bbox"]]

    # convert list of bbox to columns
    bboxes = df["bbox"].apply(pd.Series, index=["col_x", "row_y", "width", "height"])

    # combine dataframes
    df = df.drop(columns=["bbox"]).join(bboxes, validate="1:1")

    df["label"] = "drone"
    return df


def prepare_annotations(root_dir: pathlib.Path):
    annotation_dir = root_dir / "annotations"

    result = pd.DataFrame()
    for subset, split in SPLIT_MAP.items():
        subset_file = annotation_dir / f"{subset}.json"
        if not subset_file.exists():
            warnings.warn(f"The subset {subset} is not found.")
            continue

        with open(subset_file, "r") as f:
            content = json.load(f)

        images = process_images(content)
        annotations = process_annotations(content)
        df = images.merge(annotations, on="image_id", validate="1:m")

        df["split"] = split
        df = df.drop(columns=["image_id"])

        result = pd.concat([result, df], ignore_index=True)
    return result

In [12]:
root_dir = pathlib.Path("~/data/UAV/DDS").expanduser()
work_dir = pathlib.Path("~/work/work_dirs/fastdup/dds").expanduser()

annotations = prepare_annotations(root_dir)
# annotation_dir = root_dir / "annotations"
# annotations = [annotation_dir / "train.json", annotation_dir]

fd = fastdup.create(input_dir=root_dir / "images", work_dir=work_dir)
fd.run(annotations=annotations)

/tmp/ipykernel_2102940/3047095884.py:32: UserWarning: The subset test is not found.
  warnings.warn(f"The subset {subset} is not found.")

FastDup Software, (C) copyright 2022 Dr. Amir Alush and Dr. Danny Bickson.
2024-06-02 22:35:29 [INFO] Going to loop over dir /tmp/tmps4ful5h0.csv
2024-06-02 22:35:29 [INFO] Found total 23873 images to run on, 23873 train, 0 test, name list 23873, counter 23873
2024-06-02 22:35:35 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/00_06_10_to_00_06_27/00490.png. Please check bounding box file -5 1238 53 93
2024-06-02 22:40:16 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_09_02_C0002_3700_mavic/00925.png. Please check bounding box file -3 2260 25 40
2024-06-02 22:41:02 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_1700_matrice/00900.png. Please check bounding box file -9 1800 75 83
2024-06-02 22:41:34 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_1700_matrice/01365.png. Please check bounding box file -11 1289 72 107
2024-06-02 22:41:39 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_1700_matrice/01360.png. Please check bounding box file -10 1282 95 120
2024-06-02 22:41:58 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_3633_inspire/00245.png. Please check bounding box file -91 1860 761 1202
2024-06-02 22:42:00 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_3633_inspire/00250.png. Please check bounding box file -42 1787 866 1213
2024-06-02 22:42:02 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_3633_inspire/00300.png. Please check bounding box file -12 1305 921 1350
2024-06-02 22:42:06 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_3633_inspire/00240.png. Please check bounding box file -57 1682 656 1191
2024-06-02 22:42:07 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_3633_inspire/00305.png. Please check bounding box file -16 1170 934 1342
2024-06-02 22:42:19 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_10_16_C0003_3633_inspire/00290.png. Please check bounding box file -61 1683 755 1331
2024-06-02 22:45:52 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_11_14_C0001_3922_matrice/01315.png. Please check bounding box file -6 1057 64 98
2024-06-02 22:45:55 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_11_14_C0001_3922_matrice/01395.png. Please check bounding box file -1 1378 69 105
2024-06-02 22:47:01 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/custom_fixed_wing_1/01420.png. Please check bounding box file -6 559 31 50
2024-06-02 22:47:02 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/custom_fixed_wing_2/00350.png. Please check bounding box file -10 334 35 28
2024-06-02 22:47:03 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/custom_fixed_wing_2/00500.png. Please check bounding box file -1 406 37 56
2024-06-02 22:47:04 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/custom_fixed_wing_2/00505.png. Please check bounding box file -13 398 37 57
2024-06-02 22:47:05 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/custom_fixed_wing_2/01130.png. Please check bounding box file -13 397 36 38
2024-06-02 22:47:06 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/custom_fixed_wing_2/01415.png. Please check bounding box file -17 419 33 34
2024-06-02 22:50:16 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/dji_phantom_4_hillside_cross/02095.png. Please check bounding box file 141 -31 46 61
2024-06-02 22:50:21 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/dji_phantom_4_hillside_cross/02350.png. Please check bounding box file -1 1019 34 49
2024-06-02 22:50:22 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/dji_phantom_4_hillside_cross/02360.png. Please check bounding box file -1 707 34 49
2024-06-02 22:51:46 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/GOPR5842_007/00430.png. Please check bounding box file -2 13 27 29
2024-06-02 22:55:18 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/matrice_600_3/02590.png. Please check bounding box file -2 223 15 33
2024-06-02 22:55:19 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/matrice_600_3/02595.png. Please check bounding box file -5 219 16 33
2024-06-02 22:55:19 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/matrice_600_3/02600.png. Please check bounding box file -7 216 16 34
2024-06-02 22:55:23 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/parot_disco_takeoff/00085.png. Please check bounding box file -11 261 32 149
2024-06-02 22:55:29 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/parrot_clear_birds/00365.png. Please check bounding box file -7 1067 20 24
2024-06-02 22:56:36 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/parrot_disco_midrange_cross/02485.png. Please check bounding box file -7 283 15 32
2024-06-02 22:56:56 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/swarm_dji_phantom/03715.png. Please check bounding box file -2 468 12 12
2024-06-02 22:56:56 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/swarm_dji_phantom/03720.png. Please check bounding box file -3 468 11 11
2024-06-02 22:56:56 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/swarm_dji_phantom/03725.png. Please check bounding box file -7 466 12 12
2024-06-02 22:56:58 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/two_parrot_disco_1/01515.png. Please check bounding box file -1 25 27 29
2024-06-02 22:56:58 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/two_parrot_disco_1/02380.png. Please check bounding box file -17 428 31 40
2024-06-02 22:56:59 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/two_parrot_disco_1/02480.png. Please check bounding box file -1 649 28 37
2024-06-02 22:57:37 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_09_02_C0002_2527_inspire/00225.png. Please check bounding box file -5 3678 28 47
2024-06-02 22:57:38 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_09_02_C0002_2527_inspire/00230.png. Please check bounding box file -4 3643 39 64
2024-06-02 22:57:39 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/2019_09_02_C0002_2527_inspire/00200.png. Please check bounding box file -18 3700 47 58
2024-06-02 22:58:05 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/distant_parrot_2/00755.png. Please check bounding box file 872 -43 28 68
2024-06-02 23:00:06 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/swarm_dji_phantom4_2/01945.png. Please check bounding box file -5 606 16 21
2024-06-02 23:00:06 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/swarm_dji_phantom4_2/02090.png. Please check bounding box file -6 232 15 21
2024-06-02 23:00:06 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/swarm_dji_phantom4_2/02085.png. Please check bounding box file -2 240 17 24
2024-06-02 23:00:11 [WARNING] Found invalid bounding box for image /home/leafying/data/UAV/DDS/images/two_distant_phantom/01040.png. Please check bounding box file 465 -3 28 25
FastDup Software, (C) copyright 2022 Dr. Amir Alush and Dr. Danny Bickson.tes
2024-06-02 23:00:16 [INFO] Going to loop over dir /tmp/crops_input.csv
2024-06-02 23:00:17 [INFO] Found total 22418 images to run on, 22418 train, 0 test, name list 22418, counter 22418
2024-06-02 23:00:48 [INFO] Found total 22418 images to run onimated: 0 Minutes
Finished histogram 9.584
Finished bucket sort 9.655
2024-06-02 23:00:49 [INFO] 658) Finished write_index() NN model
2024-06-02 23:00:49 [INFO] Stored nn model index file /home/leafying/work/work_dirs/fastdup/dds/nnf.index
2024-06-02 23:00:49 [INFO] Total time took 32356 ms
2024-06-02 23:00:49 [INFO] Found a total of 4026 fully identical images (d>0.990), which are 8.98 % of total graph edges
2024-06-02 23:00:49 [INFO] Found a total of 9557 nearly identical images(d>0.980), which are 21.32 % of total graph edges
2024-06-02 23:00:49 [INFO] Found a total of 43244 above threshold images (d>0.900), which are 96.45 % of total graph edges
2024-06-02 23:00:49 [INFO] Found a total of 2241 outlier images         (d<0.050), which are 5.00 % of total graph edges
2024-06-02 23:00:49 [INFO] Min similarity found 0.442 max similarity 1.000
2024-06-02 23:00:49 [INFO] Running connected components for ccthreshold 0.960000
.0
 ########################################################################################

Dataset Analysis Summary:

    Dataset contains 23873 objects
    Valid objects are 93.91% (22,418) of the data, invalid are 6.09% (1,455) of the data
    For a detailed analysis, use `.invalid_instances()`.

    Components:  failed to find images clustered into components, try to run with lower cc_threshold.
    Outliers: 5.85% (1,397) of images are possible outliers, and fall in the bottom 5.00% of similarity values.
    For a detailed list of outliers, use `.outliers()`.

########################################################################################
Would you like to see awesome visualizations for some of the most popular academic datasets?
Click here to see and learn more: https://app.visual-layer.com/vl-datasets?utm_source=fastdup
########################################################################################

0

In [13]:
fd.vis.similarity_gallery()

Warning: you are running create_similarity_gallery() without providing get_label_func so similarities are not computed between different classes. It is recommended to run this report with labels. Without labels this report output is similar to create_duplicate_gallery()

Generating gallery:   0%|          | 0/20 [00:00<?, ?it/s]

Stored similar images visual view in  /home/leafying/work/work_dirs/fastdup/dds/galleries/similarity.html
########################################################################################
Would you like to see awesome visualizations for some of the most popular academic datasets?
Click here to see and learn more: https://app.visual-layer.com/vl-datasets?utm_source=fastdup
########################################################################################

                                                                                                                                         from                                                                                                                                                                                                                                                                                  to           label          label2              distance
3902       /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_matrice_210_hillside00175.png_1228_479_88_66.jpg            [/home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_matrice_210_hillside00140.png_1102_476_85_65.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_matrice_210_hillside00180.png_1245_481_90_68.jpg]  [drone, drone]  [drone, drone]    [0.900038, 0.9145]
2299                   /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesGOPR5842_00200055.png_1305_273_42_37.jpg                                                                                                                                                            [/home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesGOPR5842_00200050.png_1334_257_39_36.jpg]         [drone]         [drone]            [0.900046]
3962       /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_matrice_210_hillside00490.png_1255_490_71_54.jpg            [/home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_matrice_210_hillside00480.png_1275_508_71_52.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_matrice_210_hillside00465.png_1239_533_61_52.jpg]  [drone, drone]  [drone, drone]  [0.900085, 0.905329]
1810  /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_11_14_C0001_3922_matrice00055.png_1875_873_56_30.jpg  [/home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_11_14_C0001_3922_matrice00065.png_2011_779_54_31.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_11_14_C0001_3922_matrice00050.png_1804_917_56_31.jpg]  [drone, drone]  [drone, drone]  [0.900087, 0.906884]
6758      /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_phantom_4_long_takeoff01090.png_844_711_18_13.jpg          [/home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_phantom_4_long_takeoff00980.png_866_868_14_12.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimagesdji_phantom_4_long_takeoff01070.png_861_763_11_12.jpg]  [drone, drone]  [drone, drone]  [0.900118, 0.906741]
...                                                                                                                                       ...                                                                                                                                                                                                                                                                                 ...             ...             ...                   ...
1652   /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_10_16_C0003_4613_mavic00005.png_2133_983_183_78.jpg    [/home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_10_16_C0003_4613_mavic00000.png_2133_983_183_78.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_10_16_C0003_4613_mavic00010.png_2133_983_183_78.jpg]  [drone, drone]  [drone, drone]       [0.999935, 1.0]
1653   /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_10_16_C0003_4613_mavic00010.png_2133_983_183_78.jpg    [/home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_10_16_C0003_4613_mavic00000.png_2133_983_183_78.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/0/homeleafyingdataUAVDDSimages2019_10_16_C0003_4613_mavic00005.png_2133_983_183_78.jpg]  [drone, drone]  [drone, drone]       [0.999935, 1.0]
9817   /home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00005.png_688_454_13_11.jpg    [/home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00010.png_688_454_13_11.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00000.png_688_454_13_11.jpg]  [drone, drone]  [drone, drone]            [1.0, 1.0]
9816   /home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00000.png_688_454_13_11.jpg    [/home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00010.png_688_454_13_11.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00005.png_688_454_13_11.jpg]  [drone, drone]  [drone, drone]            [1.0, 1.0]
9818   /home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00010.png_688_454_13_11.jpg    [/home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00005.png_688_454_13_11.jpg, /home/leafying/work/work_dirs/fastdup/dds/crops/1/homeleafyingdataUAVDDSimages2019_09_02_GOPR5871_1058_solo00000.png_688_454_13_11.jpg]  [drone, drone]  [drone, drone]            [1.0, 1.0]

[21828 rows x 5 columns]

In [14]:
fd.vis.component_gallery(metric="size")

drone

Generating gallery:   0%|          | 0/20 [00:00<?, ?it/s]

Finished OK. Components are stored as image files /home/leafying/work/work_dirs/fastdup/dds/galleries/components_[index].jpg
Stored components visual view in  /home/leafying/work/work_dirs/fastdup/dds/galleries/components.html
Execution time in seconds 1.6
########################################################################################
Would you like to see awesome visualizations for some of the most popular academic datasets?
Click here to see and learn more: https://app.visual-layer.com/vl-datasets?utm_source=fastdup
########################################################################################

0

In [15]:
fd.vis.duplicates_gallery()

Generating gallery:   0%|          | 0/20 [00:00<?, ?it/s]

Stored similarity visual view in  /home/leafying/work/work_dirs/fastdup/dds/galleries/duplicates.html
########################################################################################
Would you like to see awesome visualizations for some of the most popular academic datasets?
Click here to see and learn more: https://app.visual-layer.com/vl-datasets?utm_source=fastdup
########################################################################################

0

In [16]:
fd.vis.outliers_gallery()

Generating gallery:   0%|          | 0/20 [00:00<?, ?it/s]

Stored outliers visual view in  /home/leafying/work/work_dirs/fastdup/dds/galleries/outliers.html
########################################################################################
Would you like to see awesome visualizations for some of the most popular academic datasets?
Click here to see and learn more: https://app.visual-layer.com/vl-datasets?utm_source=fastdup
########################################################################################

0

In [17]:
fd.invalid_instances()

       col_x  row_y  width  height  label  split crop_filename filename  index  is_valid
24      1879    290     56      46  drone  train           NaN      NaN    NaN     False
71      1238     -5     93      53  drone  train           NaN      NaN    NaN     False
255      410    735     17       9  drone  train           NaN      NaN    NaN     False
265      393    738     16       9  drone  train           NaN      NaN    NaN     False
266      391    739     16       8  drone  train           NaN      NaN    NaN     False
...      ...    ...    ...     ...    ...    ...           ...      ...    ...       ...
21837    969    836      5       4  drone    val           NaN      NaN    NaN     False
22505    606     -5     21      16  drone    val           NaN      NaN    NaN     False
22560    240     -2     24      17  drone    val           NaN      NaN    NaN     False
22562    232     -6     21      15  drone    val           NaN      NaN    NaN     False
23176     -3    465     25      28  drone    val           NaN      NaN    NaN     False

[1455 rows x 10 columns]